"""Semantic control fixtures for native appearance-editor actions."""

from .constants import (
    APPEARANCE_FIELD_BACKGROUND_COLOR,
    APPEARANCE_WIDGET_DEFAULT_SCOPE_PREFIX,
    APPEARANCE_WIDGET_SCOPE_PREFIX,
    FIXTURE_HOME_PAGE_ID,
)


APPEARANCE_ACTIONS_ARTIFACT_NAME = "appearance-actions.png"
APPEARANCE_ACTIONS_MCP_REQUEST_ID = 93
APPEARANCE_ACTIONS_RESET = "reset"
APPEARANCE_ACTIONS_ROLE_BUTTON = "button"
APPEARANCE_ACTIONS_SAVE = "save"
APPEARANCE_ACTIONS_SEPARATOR = ":"
APPEARANCE_ACTIONS_WIDGET_ID = "welcome"
APPEARANCE_ACTIONS_WIDGET_PREFIX = "widget:"
APPEARANCE_ACTIONS_WIDGET_SEMANTIC_ID = (
    f"{APPEARANCE_ACTIONS_WIDGET_PREFIX}{APPEARANCE_ACTIONS_WIDGET_ID}"
)
APPEARANCE_ACTIONS_PAGE_MENU_SETTINGS_SEMANTIC_ID = (
    f"page:menu:{FIXTURE_HOME_PAGE_ID}:settings"
)


def appearance_action_semantic_id(scope: str, action: str) -> str:
    return f"{scope}{APPEARANCE_ACTIONS_SEPARATOR}{action}"


APPEARANCE_ACTIONS_WIDGET_BACKGROUND_COLOR_SEMANTIC_ID = appearance_action_semantic_id(
    APPEARANCE_WIDGET_SCOPE_PREFIX,
    APPEARANCE_FIELD_BACKGROUND_COLOR,
)
APPEARANCE_ACTIONS_DEFAULT_BACKGROUND_COLOR_SEMANTIC_ID = appearance_action_semantic_id(
    APPEARANCE_WIDGET_DEFAULT_SCOPE_PREFIX,
    APPEARANCE_FIELD_BACKGROUND_COLOR,
)
APPEARANCE_ACTIONS_WIDGET_SAVE_SEMANTIC_ID = appearance_action_semantic_id(
    APPEARANCE_WIDGET_SCOPE_PREFIX,
    APPEARANCE_ACTIONS_SAVE,
)
APPEARANCE_ACTIONS_WIDGET_RESET_SEMANTIC_ID = appearance_action_semantic_id(
    APPEARANCE_WIDGET_SCOPE_PREFIX,
    APPEARANCE_ACTIONS_RESET,
)
APPEARANCE_ACTIONS_DEFAULT_SAVE_SEMANTIC_ID = appearance_action_semantic_id(
    APPEARANCE_WIDGET_DEFAULT_SCOPE_PREFIX,
    APPEARANCE_ACTIONS_SAVE,
)
APPEARANCE_ACTIONS_DEFAULT_RESET_SEMANTIC_ID = appearance_action_semantic_id(
    APPEARANCE_WIDGET_DEFAULT_SCOPE_PREFIX,
    APPEARANCE_ACTIONS_RESET,
)
