"""Device-configuration fixtures for the isolated Android emulator."""

AUTOMATION_DEVICE_CONFIGURATION_CAPABILITY = "deviceConfiguration"
AUTOMATION_DEVICE_CONFIGURATION_COALESCING_KEY = "device-configuration"
AUTOMATION_DEVICE_CONFIGURATION_EVENT = "deviceConfiguration"
AUTOMATION_DEVICE_CONFIGURATION_INITIAL_STATE = {
    "orientation": "waiting",
    "fontScalePercent": -1,
}
AUTOMATION_DEVICE_CONFIGURATION_MCP_CONFIG_GET_REQUEST_ID = 70
AUTOMATION_DEVICE_CONFIGURATION_SOURCE = (
    'function on_event(event)\n'
    f'  if event.type ~= "{AUTOMATION_DEVICE_CONFIGURATION_EVENT}" then return end\n'
    '  return { type = "patchState", values = { '
    'orientation = event.payload.orientation, fontScalePercent = event.payload.fontScalePercent } }\n'
    'end'
)
AUTOMATION_DEVICE_CONFIGURATION_FONT_SCALE_PERCENT_STATE_KEY = "fontScalePercent"
AUTOMATION_DEVICE_CONFIGURATION_STATE_KEY = "orientation"
DEVICE_CONFIGURATION_FONT_SCALE_ARTIFACT_NAME = "device-configuration-font-scale.png"
EMULATOR_DEVICE_FONT_SCALE_PERCENT_BASELINE = 100
EMULATOR_DEVICE_FONT_SCALE_PERCENT_ENLARGED = 130
EMULATOR_DEVICE_FONT_SCALE_PERCENT_SMALL = 85
EMULATOR_DEVICE_FONT_SCALE_PERCENTAGES = frozenset(
    {
        EMULATOR_DEVICE_FONT_SCALE_PERCENT_SMALL,
        EMULATOR_DEVICE_FONT_SCALE_PERCENT_BASELINE,
        EMULATOR_DEVICE_FONT_SCALE_PERCENT_ENLARGED,
    },
)
EMULATOR_DEVICE_ORIENTATION_LANDSCAPE = "landscape"
EMULATOR_DEVICE_ORIENTATION_PORTRAIT = "portrait"
EMULATOR_DEVICE_ORIENTATIONS = frozenset(
    {
        EMULATOR_DEVICE_ORIENTATION_LANDSCAPE,
        EMULATOR_DEVICE_ORIENTATION_PORTRAIT,
    },
)
