"""Do Not Disturb interruption-filter fixtures for the isolated Android emulator."""

AUTOMATION_INTERRUPTION_FILTER_CAPABILITY = "interruptionFilterState"
AUTOMATION_INTERRUPTION_FILTER_COALESCING_KEY = "interruption-filter"
AUTOMATION_INTERRUPTION_FILTER_EVENT = "interruptionFilter"
AUTOMATION_INTERRUPTION_FILTER_INITIAL_STATE = {"interruptionFilter": "waiting"}
AUTOMATION_INTERRUPTION_FILTER_MCP_CONFIG_GET_REQUEST_ID = 64
AUTOMATION_INTERRUPTION_FILTER_SOURCE = (
    'function on_event(event)\n'
    f'  if event.type ~= "{AUTOMATION_INTERRUPTION_FILTER_EVENT}" then return end\n'
    '  return { type = "patchState", values = { interruptionFilter = event.payload.mode } }\n'
    'end'
)
AUTOMATION_INTERRUPTION_FILTER_STATE_KEY = "interruptionFilter"
EMULATOR_INTERRUPTION_FILTER_ALL = "all"
EMULATOR_INTERRUPTION_FILTER_PRIORITY = "priority"
EMULATOR_INTERRUPTION_FILTER_ALARMS = "alarms"
EMULATOR_INTERRUPTION_FILTER_NONE = "none"
EMULATOR_INTERRUPTION_FILTERS = frozenset(
    (
        EMULATOR_INTERRUPTION_FILTER_ALL,
        EMULATOR_INTERRUPTION_FILTER_PRIORITY,
        EMULATOR_INTERRUPTION_FILTER_ALARMS,
        EMULATOR_INTERRUPTION_FILTER_NONE,
    ),
)
EMULATOR_NOTIFICATION_POLICY_ACCESS_GRANTED = "granted"
EMULATOR_NOTIFICATION_POLICY_ACCESS_REVOKED = "revoked"
EMULATOR_NOTIFICATION_POLICY_ACCESS_STATES = frozenset(
    (
        EMULATOR_NOTIFICATION_POLICY_ACCESS_GRANTED,
        EMULATOR_NOTIFICATION_POLICY_ACCESS_REVOKED,
    ),
)
