"""Semantic control fixtures for the native page-rename dialog."""

from .constants import FIXTURE_NOTES_PAGE_ID, PAGE_MENU_ACTION_PREFIX


PAGE_RENAME_ARTIFACT_NAME = "page-rename-controls.png"
PAGE_RENAME_MCP_REQUEST_ID = 94
PAGE_RENAME_PREFIX = "page:rename:"
PAGE_RENAME_ROLE_BUTTON = "button"
PAGE_RENAME_ROLE_TEXT_INPUT = "textInput"
PAGE_RENAME_SAVE = "save"
PAGE_RENAME_SEPARATOR = ":"
PAGE_RENAME_TITLE = "title"
PAGE_RENAME_PAGE_ID = FIXTURE_NOTES_PAGE_ID
PAGE_RENAME_PAGE_MENU_SEMANTIC_ID = (
    f"{PAGE_MENU_ACTION_PREFIX}{PAGE_RENAME_PAGE_ID}:rename"
)
PAGE_RENAME_TITLE_REPLACEMENT = "Renamed from native dialog"
PAGE_RENAME_TITLE_SEMANTIC_ID = (
    f"{PAGE_RENAME_PREFIX}{PAGE_RENAME_PAGE_ID}{PAGE_RENAME_SEPARATOR}{PAGE_RENAME_TITLE}"
)
PAGE_RENAME_SAVE_SEMANTIC_ID = (
    f"{PAGE_RENAME_PREFIX}{PAGE_RENAME_PAGE_ID}{PAGE_RENAME_SEPARATOR}{PAGE_RENAME_SAVE}"
)
