"""Widget-lock control fixtures for the isolated Android emulator."""

WIDGET_LOCKS_ACTION_SAVE = "save"
WIDGET_LOCKS_ACTION_WIDGET = "widget"
WIDGET_LOCKS_ARTIFACT_NAME = "widget-locks-control.png"
WIDGET_LOCKS_MCP_SNAPSHOT_REQUEST_ID = 72
WIDGET_LOCKS_MCP_TAP_REQUEST_ID = 73
WIDGET_LOCKS_NOTES_PAGE_ID = "notes"
WIDGET_LOCKS_NOTES_WIDGET_ID = "notes-intro"
WIDGET_LOCKS_ROLE_BUTTON = "button"
WIDGET_LOCKS_ROLE_SWITCH = "switch"
WIDGET_LOCKS_SEMANTIC_PREFIX = "page:widget-locks:"
WIDGET_LOCKS_SEMANTIC_SEPARATOR = ":"
WIDGET_LOCKS_NOTES_WIDGET_SEMANTIC_ID = (
    f"{WIDGET_LOCKS_SEMANTIC_PREFIX}{WIDGET_LOCKS_NOTES_PAGE_ID}"
    f"{WIDGET_LOCKS_SEMANTIC_SEPARATOR}{WIDGET_LOCKS_ACTION_WIDGET}"
    f"{WIDGET_LOCKS_SEMANTIC_SEPARATOR}{WIDGET_LOCKS_NOTES_WIDGET_ID}"
)
WIDGET_LOCKS_NOTES_SAVE_SEMANTIC_ID = (
    f"{WIDGET_LOCKS_SEMANTIC_PREFIX}{WIDGET_LOCKS_NOTES_PAGE_ID}"
    f"{WIDGET_LOCKS_SEMANTIC_SEPARATOR}{WIDGET_LOCKS_ACTION_SAVE}"
)
